spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rems
    username: root
    password: zlzzf
  mail:
    host: smtp.163.com
    port: 465
    username: remsSVIP@163.com
    password: LERVWPXGTYCRXPRQ
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
file:
  #静态资源对外暴露的访问路径
  staticAccessPath: /api/file/**
  ###静态资源实际存储路径
  uploadFolder: D:/remsFile/
  ###虚拟路径
  virtualPath: http://localhost:8080

frontend:
  #前端访问路径
  frontendAccessPath: http://localhost:5173



